- type: roleLoadout
  id: JobHeadOfSecurity
  groups:
  - SurvivalSecurity
  - GroupSpeciesBreathToolSecurity
  - HeadofSecurityHead
  - SecurityGlasses
  # Mask
  - HeadofSecurityNeck
  # Gloves
  - HeadofSecurityJumpsuit
  - SecurityBackpack
  # PDA
  - SecurityBelt
  - HeadofSecurityOuterClothing
  - SecurityShoes
  - Trinkets
  - CommandPets
