- type: antag
  id: Vampire
  name: roles-antag-vampire-name
  antagonist: true
  setPreference: true
  objective: roles-antag-vampire-objective
  guides: [ Vampire ]
  requirements:
  - !type:OverallPlaytimeRequirement
    time: 3600 # 1h